<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function commerce_agree_terms_commerce_checkout_pane_info() {
  $checkout_panes = array();

  $checkout_panes['terms_conditions'] = array(
    'title' => variable_get('commerce_agree_terms_pane_title', t('Terms and Conditions')),
    'base' => 'commerce_agree_terms_pane',
    'page' => 'checkout',
    'weight' => '-10',
    'fieldset' => TRUE,
    'file' => 'includes/commerce_agree_terms.checkout_pane.inc',
  );

  return $checkout_panes;
}

/**
 * Implements hook_menu().
 */
function commerce_agree_terms_menu() {
  $items = array();

  if (module_exists('i18n_variable')) {
    $items['admin/commerce/config/checkout/terms_conditions'] = array(
      'title' => 'Commerce Agree Terms multilingual',
      'description' => 'Administer Commerce Agree Terms.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('variable_group_form', 'commerce_agree_terms'),
      'access arguments' => array('configure store'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => 99,
    );
  }

  return $items;
}
